// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xhwaccel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHwaccel_CfgInitialize(XHwaccel *InstancePtr, XHwaccel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi_l_BaseAddress = ConfigPtr->Axi_l_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHwaccel_Start(XHwaccel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL) & 0x80;
    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHwaccel_IsDone(XHwaccel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHwaccel_IsIdle(XHwaccel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHwaccel_IsReady(XHwaccel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHwaccel_EnableAutoRestart(XHwaccel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL, 0x80);
}

void XHwaccel_DisableAutoRestart(XHwaccel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_AP_CTRL, 0);
}

u32 XHwaccel_Get_s_screen_val_BaseAddress(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE);
}

u32 XHwaccel_Get_s_screen_val_HighAddress(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH);
}

u32 XHwaccel_Get_s_screen_val_TotalBytes(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + 1);
}

u32 XHwaccel_Get_s_screen_val_BitWidth(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHWACCEL_AXI_L_WIDTH_S_SCREEN_VAL;
}

u32 XHwaccel_Get_s_screen_val_Depth(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHWACCEL_AXI_L_DEPTH_S_SCREEN_VAL;
}

u32 XHwaccel_Write_s_screen_val_Words(XHwaccel *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XHwaccel_Read_s_screen_val_Words(XHwaccel *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XHwaccel_Write_s_screen_val_Bytes(XHwaccel *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XHwaccel_Read_s_screen_val_Bytes(XHwaccel *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_SCREEN_VAL_BASE + offset + i);
    }
    return length;
}

u32 XHwaccel_Get_s_mask_val_BaseAddress(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE);
}

u32 XHwaccel_Get_s_mask_val_HighAddress(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH);
}

u32 XHwaccel_Get_s_mask_val_TotalBytes(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + 1);
}

u32 XHwaccel_Get_s_mask_val_BitWidth(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHWACCEL_AXI_L_WIDTH_S_MASK_VAL;
}

u32 XHwaccel_Get_s_mask_val_Depth(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHWACCEL_AXI_L_DEPTH_S_MASK_VAL;
}

u32 XHwaccel_Write_s_mask_val_Words(XHwaccel *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XHwaccel_Read_s_mask_val_Words(XHwaccel *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XHwaccel_Write_s_mask_val_Bytes(XHwaccel *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XHwaccel_Read_s_mask_val_Bytes(XHwaccel *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHWACCEL_AXI_L_ADDR_S_MASK_VAL_HIGH - XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axi_l_BaseAddress + XHWACCEL_AXI_L_ADDR_S_MASK_VAL_BASE + offset + i);
    }
    return length;
}

void XHwaccel_InterruptGlobalEnable(XHwaccel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_GIE, 1);
}

void XHwaccel_InterruptGlobalDisable(XHwaccel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_GIE, 0);
}

void XHwaccel_InterruptEnable(XHwaccel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_IER);
    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_IER, Register | Mask);
}

void XHwaccel_InterruptDisable(XHwaccel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_IER);
    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_IER, Register & (~Mask));
}

void XHwaccel_InterruptClear(XHwaccel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwaccel_WriteReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_ISR, Mask);
}

u32 XHwaccel_InterruptGetEnabled(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_IER);
}

u32 XHwaccel_InterruptGetStatus(XHwaccel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwaccel_ReadReg(InstancePtr->Axi_l_BaseAddress, XHWACCEL_AXI_L_ADDR_ISR);
}

