# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Smartgit/RTS-/TestProject/Hello_World/Hello_World.srcs/sources_1/bd/Design_first/ip/Design_first_processing_system7_0_0/Design_first_processing_system7_0_0.xci
# IP: The module: 'Design_first_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Smartgit/RTS-/TestProject/Hello_World/Hello_World.srcs/sources_1/bd/Design_first/ip/Design_first_processing_system7_0_0/Design_first_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_first_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Smartgit/RTS-/TestProject/Hello_World/Hello_World.srcs/sources_1/bd/Design_first/ip/Design_first_processing_system7_0_0/Design_first_processing_system7_0_0.xci
# IP: The module: 'Design_first_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Smartgit/RTS-/TestProject/Hello_World/Hello_World.srcs/sources_1/bd/Design_first/ip/Design_first_processing_system7_0_0/Design_first_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_first_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
