# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Design_first/Design_first.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Design_first || ORIG_REF_NAME==Design_first} -quiet] -quiet

# IP: bd/Design_first/ip/Design_first_processing_system7_0_1/Design_first_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Design_first_processing_system7_0_1 || ORIG_REF_NAME==Design_first_processing_system7_0_1} -quiet] -quiet

# XDC: bd/Design_first/Design_first_ooc.xdc
